# Generated by Django 4.2.26 on 2025-12-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packaging',
            field=models.CharField(blank=True, help_text='Packaging type (e.g. Box, Piece)', max_length=50, null=True),
        ),
    ]
