# Generated by Django 4.2.26 on 2025-12-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_remove_invoice_order_remove_saleorder_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='packaging',
            field=models.CharField(blank=True, choices=[('Box', 'Box'), ('Piece', 'Piece'), ('Packet', 'Packet'), ('Carton', 'Carton'), ('Dozen', 'Dozen'), ('Kg', 'Kg'), ('Bag', 'Bag'), ('Bundle', 'Bundle'), ('Roll', 'Roll')], max_length=50, null=True),
        ),
    ]
