# Generated by Django 4.2.26 on 2025-12-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleitem_packaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='packaging',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
